user www;
worker_processes 1;
events {
 worker_connections 1024;
}

http {
 include mime.types;
 default_type application/octet-stream;
 sendfile on;
 keepalive_timeout  65;
 gzip on;
 server_tokens off;
 client_max_body_size 100M;

 server {
 # Serviert HTTPS Redirect zu https://feinste-netzwerke.de
  listen 80 default_server;
  #listen [::]:80;
  server_name feinste-netzwerke.de;
  include letsencrypt.conf;
  return 301 https://$host$request_uri;
 }

 server {
 # Serviert Proxy zum feinste-netzwerke.de SNAC Server
  listen 443 ssl;
  #listen [::]:443 ssl;
  http2 on;
  server_name feinste-netzwerke.de;
  include nginx-ssl.conf;
  include letsencrypt.conf;
  location / {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  location = /favicon.ico {
   alias /usr/local/www/cclogo4_fav.png;
   }
  # webfinger
  location /.well-known/webfinger {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # Mastodon API (entry points)
  location /api/v1 {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  location /api/v2 {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # Mastodon API (OAuth support)
  location /oauth {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # optional
  location /.well-known/nodeinfo {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # optional (needed by some Mastodon API clients)
  location /.well-known/host-meta {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # optional (Mastodon-like link share entrypoint)
  location /share {
   proxy_pass http://10.0.0.16:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  # optional (Mastodon-like "authorize interaction" entrypoint)
  location /authorize_interaction {
   proxy_pass http://10.0.0.17:8001;
   proxy_set_header Host $http_host;
   proxy_set_header X-Forwarded-For $remote_addr;
   proxy_set_header X-Real-IP $remote_addr;
   }
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
   root /usr/local/www/nginx-dist;
   }
  ssl_trusted_certificate /usr/local/etc/ssl/computing-competence.de/ecc/ca.pem; # CA Cert
  ssl_certificate /usr/local/etc/ssl/computing-competence.de/fullchain.pem; # RSA Cert
  ssl_certificate /usr/local/etc/ssl/computing-competence.de/ecc/fullchain.pem; # ECDSA Cert
  ssl_certificate_key /usr/local/etc/ssl/computing-competence.de/key.pem; # RSA Key
  ssl_certificate_key /usr/local/etc/ssl/computing-competence.de/ecc/key.pem; # ECDSA Key
  ssl_dhparam /usr/local/etc/ssl/computing-competence.de/dhparam.pem; # 4096b Diffie-Hellman parameter
 }

}
